[phases.setup]
nixPkgs = [
  "python311",
  "pango",
  "cairo",
  "gdk-pixbuf",
  "libffi",
  "glib",
  "gobject-introspection",
  "harfbuzz",
  "fontconfig",
  "freetype",
  "shared-mime-info",
  "zlib",
]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt",
]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT"
